// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"smartpower/diagram/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AppAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/cabdata",
					Handler: CabDataHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/strucdata",
					Handler: StructDataHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/diagram/v1"),
	)
}
