// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: proto/device.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{0}
}

type DeviceOnline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Onlines int64 `protobuf:"varint,1,opt,name=onlines,proto3" json:"onlines,omitempty"`
}

func (x *DeviceOnline) Reset() {
	*x = DeviceOnline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceOnline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceOnline) ProtoMessage() {}

func (x *DeviceOnline) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceOnline.ProtoReflect.Descriptor instead.
func (*DeviceOnline) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceOnline) GetOnlines() int64 {
	if x != nil {
		return x.Onlines
	}
	return 0
}

type DeviceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid  string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
	Code int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Flag int32  `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Dst  int32  `protobuf:"varint,4,opt,name=dst,proto3" json:"dst,omitempty"`
	Data []byte `protobuf:"bytes,5,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *DeviceData) Reset() {
	*x = DeviceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceData) ProtoMessage() {}

func (x *DeviceData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceData.ProtoReflect.Descriptor instead.
func (*DeviceData) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceData) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

func (x *DeviceData) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeviceData) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *DeviceData) GetDst() int32 {
	if x != nil {
		return x.Dst
	}
	return 0
}

func (x *DeviceData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Conn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (x *Conn) Reset() {
	*x = Conn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Conn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conn) ProtoMessage() {}

func (x *Conn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conn.ProtoReflect.Descriptor instead.
func (*Conn) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{3}
}

func (x *Conn) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

type BidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid string `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (x *BidReq) Reset() {
	*x = BidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidReq) ProtoMessage() {}

func (x *BidReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidReq.ProtoReflect.Descriptor instead.
func (*BidReq) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{4}
}

func (x *BidReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

type RemoteControlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpCode int32  `protobuf:"varint,1,opt,name=opCode,proto3" json:"opCode,omitempty"`
	OpId   int32  `protobuf:"varint,2,opt,name=opId,proto3" json:"opId,omitempty"`
	Bid    string `protobuf:"bytes,3,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (x *RemoteControlReq) Reset() {
	*x = RemoteControlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteControlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteControlReq) ProtoMessage() {}

func (x *RemoteControlReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteControlReq.ProtoReflect.Descriptor instead.
func (*RemoteControlReq) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{5}
}

func (x *RemoteControlReq) GetOpCode() int32 {
	if x != nil {
		return x.OpCode
	}
	return 0
}

func (x *RemoteControlReq) GetOpId() int32 {
	if x != nil {
		return x.OpId
	}
	return 0
}

func (x *RemoteControlReq) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

type RemoteControlResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	RunningState int32 `protobuf:"varint,2,opt,name=runningState,proto3" json:"runningState,omitempty"`
	MainSwitch   int32 `protobuf:"varint,3,opt,name=mainSwitch,proto3" json:"mainSwitch,omitempty"`
}

func (x *RemoteControlResp) Reset() {
	*x = RemoteControlResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteControlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteControlResp) ProtoMessage() {}

func (x *RemoteControlResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteControlResp.ProtoReflect.Descriptor instead.
func (*RemoteControlResp) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{6}
}

func (x *RemoteControlResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RemoteControlResp) GetRunningState() int32 {
	if x != nil {
		return x.RunningState
	}
	return 0
}

func (x *RemoteControlResp) GetMainSwitch() int32 {
	if x != nil {
		return x.MainSwitch
	}
	return 0
}

type EMTimeSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*EMTimeSlot_TimeSlot `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Bid  string                 `protobuf:"bytes,2,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (x *EMTimeSlot) Reset() {
	*x = EMTimeSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EMTimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMTimeSlot) ProtoMessage() {}

func (x *EMTimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMTimeSlot.ProtoReflect.Descriptor instead.
func (*EMTimeSlot) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{7}
}

func (x *EMTimeSlot) GetList() []*EMTimeSlot_TimeSlot {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *EMTimeSlot) GetBid() string {
	if x != nil {
		return x.Bid
	}
	return ""
}

type EMTimeSlot_TimeSlot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Start int32 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End   int32 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *EMTimeSlot_TimeSlot) Reset() {
	*x = EMTimeSlot_TimeSlot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_device_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EMTimeSlot_TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMTimeSlot_TimeSlot) ProtoMessage() {}

func (x *EMTimeSlot_TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMTimeSlot_TimeSlot.ProtoReflect.Descriptor instead.
func (*EMTimeSlot_TimeSlot) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{7, 0}
}

func (x *EMTimeSlot_TimeSlot) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *EMTimeSlot_TimeSlot) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *EMTimeSlot_TimeSlot) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_proto_device_proto protoreflect.FileDescriptor

var file_proto_device_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x28, 0x0a, 0x0c, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x7a, 0x0a, 0x0a, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66,
	0x6c, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x64, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x18, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69,
	0x64, 0x22, 0x1a, 0x0a, 0x06, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x62,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x22, 0x50, 0x0a,
	0x10, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6f, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x62, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x22,
	0x6f, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c,
	0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x72, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x69, 0x6e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x22, 0x93, 0x01, 0x0a, 0x0a, 0x45, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x12,
	0x2b, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x62, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x64, 0x1a, 0x46,
	0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x32, 0xb7, 0x02, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x31, 0x0a, 0x12, 0x41, 0x6e, 0x61, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x29, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x20, 0x0a, 0x09, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x08, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x34, 0x0a, 0x1b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x4d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x43, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x15,
	0x45, 0x4d, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x69, 0x6e,
	0x67, 0x50, 0x75, 0x73, 0x68, 0x12, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x4d, 0x54, 0x69, 0x6d,
	0x65, 0x53, 0x6c, 0x6f, 0x74, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_device_proto_rawDescOnce sync.Once
	file_proto_device_proto_rawDescData = file_proto_device_proto_rawDesc
)

func file_proto_device_proto_rawDescGZIP() []byte {
	file_proto_device_proto_rawDescOnce.Do(func() {
		file_proto_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_device_proto_rawDescData)
	})
	return file_proto_device_proto_rawDescData
}

var file_proto_device_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_device_proto_goTypes = []interface{}{
	(*Empty)(nil),               // 0: pb.Empty
	(*DeviceOnline)(nil),        // 1: pb.DeviceOnline
	(*DeviceData)(nil),          // 2: pb.DeviceData
	(*Conn)(nil),                // 3: pb.Conn
	(*BidReq)(nil),              // 4: pb.BidReq
	(*RemoteControlReq)(nil),    // 5: pb.RemoteControlReq
	(*RemoteControlResp)(nil),   // 6: pb.RemoteControlResp
	(*EMTimeSlot)(nil),          // 7: pb.EMTimeSlot
	(*EMTimeSlot_TimeSlot)(nil), // 8: pb.EMTimeSlot.TimeSlot
}
var file_proto_device_proto_depIdxs = []int32{
	8, // 0: pb.EMTimeSlot.list:type_name -> pb.EMTimeSlot.TimeSlot
	0, // 1: pb.device.AnaDeviceConnected:input_type -> pb.Empty
	2, // 2: pb.device.SendToDevice:input_type -> pb.DeviceData
	3, // 3: pb.device.CloseConn:input_type -> pb.Conn
	4, // 4: pb.device.Server_MaterialList_Request:input_type -> pb.BidReq
	5, // 5: pb.device.RemoteControlRequest:input_type -> pb.RemoteControlReq
	7, // 6: pb.device.EMTimeSlotPollingPush:input_type -> pb.EMTimeSlot
	1, // 7: pb.device.AnaDeviceConnected:output_type -> pb.DeviceOnline
	0, // 8: pb.device.SendToDevice:output_type -> pb.Empty
	0, // 9: pb.device.CloseConn:output_type -> pb.Empty
	0, // 10: pb.device.Server_MaterialList_Request:output_type -> pb.Empty
	6, // 11: pb.device.RemoteControlRequest:output_type -> pb.RemoteControlResp
	0, // 12: pb.device.EMTimeSlotPollingPush:output_type -> pb.Empty
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_device_proto_init() }
func file_proto_device_proto_init() {
	if File_proto_device_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_device_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceOnline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Conn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteControlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteControlResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EMTimeSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_device_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EMTimeSlot_TimeSlot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_device_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_device_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_device_proto_goTypes,
		DependencyIndexes: file_proto_device_proto_depIdxs,
		MessageInfos:      file_proto_device_proto_msgTypes,
	}.Build()
	File_proto_device_proto = out.File
	file_proto_device_proto_rawDesc = nil
	file_proto_device_proto_goTypes = nil
	file_proto_device_proto_depIdxs = nil
}
