// Code generated by goctl. DO NOT EDIT.
package types

type IdReq struct {
	Id string `form:"id"`
}

type JsonResp struct {
	Code int      `json:"id"`
	Msg  string   `json:"msg"`
	Body JsonBody `json:"body"`
}

type JsonBody struct {
	Data string `json:"data"`
}
