// Code generated by goctl. DO NOT EDIT.
// Source: device.proto

package server

import (
	"context"

	"smartpower/device/internal/logic/device"
	"smartpower/device/internal/svc"
	"smartpower/device/pb"
)

type DeviceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedDeviceServer
}

func NewDeviceServer(svcCtx *svc.ServiceContext) *DeviceServer {
	return &DeviceServer{
		svcCtx: svcCtx,
	}
}

func (s *DeviceServer) AnaDeviceConnected(ctx context.Context, in *pb.Empty) (*pb.DeviceOnline, error) {
	l := devicelogic.NewAnaDeviceConnectedLogic(ctx, s.svcCtx)
	return l.AnaDeviceConnected(in)
}

func (s *DeviceServer) SendToDevice(ctx context.Context, in *pb.DeviceData) (*pb.Empty, error) {
	l := devicelogic.NewSendToDeviceLogic(ctx, s.svcCtx)
	return l.SendToDevice(in)
}

func (s *DeviceServer) CloseConn(ctx context.Context, in *pb.Conn) (*pb.Empty, error) {
	l := devicelogic.NewCloseConnLogic(ctx, s.svcCtx)
	return l.CloseConn(in)
}

// 服务器请求材料清单数据
func (s *DeviceServer) Server_MaterialList_Request(ctx context.Context, in *pb.BidReq) (*pb.Empty, error) {
	l := devicelogic.NewServerMaterialListRequestLogic(ctx, s.svcCtx)
	return l.Server_MaterialList_Request(in)
}

// 请求远程控制
func (s *DeviceServer) RemoteControlRequest(ctx context.Context, in *pb.RemoteControlReq) (*pb.RemoteControlResp, error) {
	l := devicelogic.NewRemoteControlRequestLogic(ctx, s.svcCtx)
	return l.RemoteControlRequest(in)
}

// 服务器下发时段配置数据 载体固定96字节
func (s *DeviceServer) EMTimeSlotPollingPush(ctx context.Context, in *pb.EMTimeSlot) (*pb.Empty, error) {
	l := devicelogic.NewEMTimeSlotPollingPushLogic(ctx, s.svcCtx)
	return l.EMTimeSlotPollingPush(in)
}
